### ISSUE TITLE
Anchor Tags and Asterisk  Tags are comming up as null on yaml.writeSync

### ISSUE THREAD

**Issue by SameerSiddiqui** [octet-stream/node-yaml#2]
I have a swagger.yaml file. With some Yaml content

I am reading that file using yaml.readSync-  Once i write it using yaml.writeSync. The original content is getting pollluted by node-yaml-

![image](https://cloud.githubusercontent.com/assets/7409374/18921942/5f594460-856c-11e6-98b3-b66ffef295e0.png)

Why node-yaml is throwing away anchor tags and just giving me nulls ? 

Also i am getting line breaks and ticks are getting inserted in the new yaml file which is written by node-yaml.

This is how it works ? 

I am trying to read the file- resolve the external refs using pointers and then write the final yaml content into another file for another project a-127 to read it and load.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
Yeah, `node-yaml` seems to be acting up!

**Comment by octet-stream** [comment]
Hello, thanks for the report!
Can you provide a way to reproduce this issue?
Which version of `node-yaml` you are using?

**Comment by octet-stream** [comment]
Closed due to no information about bug reproducing.
