### ISSUE TITLE
Relative paths broken

### ISSUE THREAD

**Issue by wiseman** [octet-stream/node-yaml#7]
Thanks for this code! 👍 

I do have a question: Why are you bothering to resolve relative paths? It seems like you're doing unnecessary work that causes problems.

For example, I assume that, like almost every program, relative paths are resolved relative to the current working directory. That's the common behavior, and the operating system handles it without you needing to write any code.  But you have this:

```
let base = process.cwd()
if (module.parent && typeof module.parent.filename === "string") {
  base = dirname(module.parent.filename)
```
And now when I do `node out/script.js", and script.js requires a module that requires `node-yaml` and contains `read("secrets.yaml")`, I get the error `ENOENT: no such file or directory, open '/Users/wiseman/src/circlebot/out/secrets.yaml'`.

I think you can remove some code, let the operating system handle relative paths, and as a bonus have less surprising behavior.

**Comment by octet-stream** [comment]
Hello! Thanks for your feedback! The read/write functions in this module works similarly to [`require`](https://nodejs.org/dist/latest-v13.x/docs/api/modules.html#modules_require_id) function from Node.js. They were designed to do so.
If you want to resolve relative paths as fs module does, try fs.readFile + load (or safeLoad) function from [`js-yaml`](https://www.npmjs.com/package/js-yaml).
