### ISSUE TITLE
js-yaml missingdependency

### ISSUE THREAD

**Issue by Coding-Kiwi** [octet-stream/node-yaml#9]
hi, your package requires 'js-yaml' but it is not listed in the package.json as dependency, would be nice if you could add it

**Comment by octet-stream** [comment]
The js-yaml package mentioned in [package.json](https://github.com/octet-stream/node-yaml/blob/beed6b1291bbe24322909aaa6da6aceea82d35ff/package.json#L35) as a peer-dependency and at [installation section](https://github.com/octet-stream/node-yaml#installation) in readme.md, so you have to install it manually. That way you can install the version you want (if my package support it)
